### ISSUE TITLE
Update ActiveRecord Syntax (Deprecated Finders)

### ISSUE THREAD

**Issue by benjaminwood** [hintmedia/rigse#14]
All dynamic methods except for find_by_... and find_by_...! are deprecated.

* 48 occurrences of `find_all_by_`
* 150 occurrences of `find_or_create_by_`.
* 87 occurrences of `find(:all....)`
* 154 uses of `:conditions =>` in various contexts (lots of scopes with conditions)
* 43 occurrences of `:order =>`

Under Rails 4, the [activerecord-deprecated_finders](https://github.com/rails/activerecord-deprecated_finders) gem can be used to but our recommendation is to resolve these issue in advance of the 4.x upgrade.

**Comment by natevick** [comment]
This issue was moved to concord-consortium/rigse#466
