### ISSUE TITLE
Update regular expressions in validates_format_of

### ISSUE THREAD

**Issue by benjaminwood** [hintmedia/rigse#19]
Rails 4 does not allow the ^ and $ anchors with a validates_format_of validation.

An ArgumentError will be raised:

> The provided regular expression is using multiline anchors (^ or $), which may present a security risk. Did you mean to use \A and \z, or forgot to add the :multiline => true option?

We found at least one example where this will be a problem in the app.

**Comment by natevick** [comment]
This issue was moved to concord-consortium/rigse#453

**Comment by natevick** [comment]
This issue was moved to concord-consortium/rigse#471
