### ISSUE TITLE
Bring testing tools/gems up to date

### ISSUE THREAD

**Issue by benjaminwood** [hintmedia/rigse#4]
Testing tools should be upgraded to most current versions supported by other dependencies on the master branch (under Rails 3.2).

For example: rspec, cucumber, and capybara are one or more major versions behind.

**Comment by natevick** [comment]
cucumber-rails is recommended to be at 1.5.0 for Rails 4.x and beyond. This will require upgrading to rspec/rspec-rails 3.x. The upgrade to rspec 3.x will require some specs to be brought up to new syntax. We have had success with using transpec gem to help with this migration.

**Comment by natevick** [comment]
This issue was moved to concord-consortium/rigse#456
