### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by benjaminwood** [hintmedia/rigse#8]
* Remove portal based authoring: remove controllers, views & assets. Authoring functionality is now contained in LARA.
* Remove portal wide researcher or guest roles (no longer supported).
* Not all Embeddables and Saveables are used. We plan to remove the unused ones before upgrading Rails.

Potentially dead:
* [config/refactoring/em.rb](https://github.com/hintmedia/rigse/blob/master/config/refactoring/em.rb)

**Comment by natevick** [comment]
This issue was moved to concord-consortium/rigse#460
