### ISSUE TITLE
Dependencies with similar/overlapping functionality

### ISSUE THREAD

**Issue by benjaminwood** [hintmedia/rigse#9]
**Ruby/Rails**

* rspec & test-unit
* cucumber & capybara
* protected_attributes & strong_parameters
* httparty & httpclient
* rollbar & exception_notification
* Devise & AuthenticatedSystem (mostly removed already)

**Javascript**
* jquery & prototype (keep jquery)
* react & angular
* select2 & chosen

**Comment by benjaminwood** [comment]
Cucumber depends on capybara, but not visa versa. Both kinds of tests are present. If cucumber is selected, then capybara should be considered a dependency and capybara specs should not be written directly.

If capybara is selected, then cucumber should be removed (and it's specs replaced).

**Comment by natevick** [comment]
This issue was moved to concord-consortium/rigse#461
